Bookers/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  get "/" => "posts#top"
  delete "posts/:id" => "posts#destroy", as: "destroy_post"
  patch "posts/:id" => "posts#update" , as: "update_post"
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/post.rb
class Post < ApplicationRecord
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers/app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def top
	end

	def index
		@post=Post.new
		@posts=Post.all
	end

	def create
		post = Post.new(post_params)
		if post.save
			flash[:notice] = "successfully"
		redirect_to post_path(post.id)
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		post = Post.find(params[:id])
		if post.update(post_params)
			flash[:notice] = "successfully"
		redirect_to post_path(post.id)
		end
	end

	def destroy
		post = Post.find(params[:id])
		post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/posts_helper.rb
module PostsHelper
end

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Bookers/app/views/posts/edit.html.erb
<div class="editpage">
	<h2>Editing Book</h2>
	<%= form_for(@post) do |f| %>

	<h3>Title</h3>
	<%= f.text_field :title %>

	<h3>Body</h3>
	<%= f.text_area :body %>

	<br><%= f.submit 'Update Book' %><br>

	<% end %>

	<div class="editpage-under">
		<%= link_to "Show", "/posts/#{@post.id}" %> |
		<%= link_to "Back", posts_path %>
	</div>

</div>

Bookers/app/views/posts/index.html.erb
<div class="post-index">
	<h1 class="post-index-title">Books</h1>
	<div class="main-top">
		<table>
			<thead>
				<tr>
					<th>Title</th>
					<th>Body</th>
					<th></th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				<% @posts.each do |post| %>
				<tr>
					<td>
						<%= post.title %>
					</td>
					<td>
						<%= post.body %>
					</td>
					<td>
						<%= link_to "Show", post_path(post.id) %>
						<%= link_to "Edit", edit_post_path(post.id) %>
						<%= link_to "Destroy", destroy_post_path(post.id), method: :delete, "date-confirm" => "Are you sure?" %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>

	<div class="main-under">
		<h2 class="main-under-title">New book</h2>
		<%= form_for(@post) do |f| %>

		<h3 class="main-under-text">Title</h3>
		<%= f.text_field :title %>

		<h3 class="main-under-text">Body</h3>
		<%= f.text_area :body %>

		<div class="main-under-br">
			<br><%= f.submit 'Create Book' %><br>
		</div>

		<% end %>
	</div>
</div>

Bookers/app/views/posts/show.html.erb
<div class="showpage">
	<div class="showpage-text">
		<p><span>Title:</span>
		<%= @post.title %>
		</p>
		<p><span>Body:</span>
		<%= @post.body %>
		</p>
	</div>

	<div class="show-edit">
		<p>
		<%= link_to "Edit", "/posts/#{@post.id}/edit" %> |
		<%= link_to "Back", posts_path %>
		</p>
	</div>
</div>
<% if flash[:notice] %>
	<div class="flash">
		<%= flash[:notice] %>
	</div>
<% end %>

Bookers/app/views/posts/top.html.erb
<div class="toppage">
	<h1 class="toppage-title">ようこそ　Bookers へ！</h1>
	<div class="sub-class">
		<p class="toppage-p"><span>Bookers</span> では、さまざまな書籍に関するあなたの意見や</p>
		<p class="toppage-p">印象を共有し交換することができます</p>
	</div>
	<div class="toppage-link">
		<%=link_to "start", posts_path %>
	</div>
</div>